site_name: DWTS App Docs
# site_url: https://samantha238.github.io/dwts-app/
site_author: Samantha Perez
site_description: >-
    Overview of development process that went into
    making the DWTS App

copyright: Copyright &copy; 2022 Samantha Perez

theme:
    name: material
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          toggle:
              icon: material/weather-night
              name: Switch to light mode

nav:
    - Home: index.md
    - App Overview:
          - Overview: overview/overview.md
          - Features: overview/features.md
    - Development:
          - Overview: dev/overview.md
          - Background: dev/background.md
          - Challenges: dev/challenges.md
    - Credit:
          - Content: credit/content.md
          - Shoutouts: credit/shoutout.md
