
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const SEARCH = 'SEARCH';
export const ADD = 'ADD';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const LIKE = 'LIKE';

export const FANSEARCH = 'FANSEARCH';

export const DANCESEARCH = 'DANCESEARCH';
export const DANCEADD = 'DANCEADD';
export const DANCEUPDATE = 'DANCEUPDATE';
export const DANCEDELETE = 'DANCEDELETE';
export const DANCELIKE = 'DANCELIKE';

export const DANCESEARCH_REQUEST = 'DANCESEARCH_REQUEST';
export const DANCESEARCH_SUCCESS = 'DANCESEARCH_SUCCESS';
export const DANCESEARCH_FAILURE = 'DANCESEARCH_FAILURE';
export const DANCEADD_REQUEST = 'DANCEADD_REQUEST';
export const DANCEADD_SUCCESS = 'DANCEADD_SUCCESS';
export const DANCEADD_FAILURE = 'DANCEADD_FAILURE';
export const DANCEUPDATE_REQUEST = 'DANCEUPDATE_REQUEST';
export const DANCEUPDATE_SUCCESS = 'DANCEUPDATE_SUCCESS';
export const DANCEUPDATE_FAILURE = 'DANCEUPDATE_FAILURE';
export const DANCEDELETE_REQUEST = 'DANCEDELETE_REQUEST';
export const DANCEDELETE_SUCCESS = 'DANCEDELETE_SUCCESS';
export const DANCEDELETE_FAILURE = 'DANCEDELETE_FAILURE';
export const DANCELIKE_REQUEST = 'DANCELIKE_REQUEST';
export const DANCELIKE_SUCCESS = 'DANCELIKE_SUCCESS';
export const DANCELIKE_FAILURE = 'DANCELIKE_FAILURE';

export const TEAMSEARCH = 'TEAMSEARCH';
export const TEAMADD = 'TEAMADD';
export const TEAMUPDATE = 'TEAMUPDATE';
export const TEAMDELETE = 'TEAMDELETE';
export const TEAMLIKE = 'TEAMLIKE';

export const TEAMSEARCH_REQUEST = 'TEAMSEARCH_REQUEST';
export const TEAMSEARCH_SUCCESS = 'TEAMSEARCH_SUCCESS';
export const TEAMSEARCH_FAILURE = 'TEAMSEARCH_FAILURE';
export const TEAMADD_REQUEST = 'TEAMADD_REQUEST';
export const TEAMADD_SUCCESS = 'TEAMADD_SUCCESS';
export const TEAMADD_FAILURE = 'TEAMADD_FAILURE';
export const TEAMUPDATE_REQUEST = 'TEAMUPDATE_REQUEST';
export const TEAMUPDATE_SUCCESS = 'TEAMUPDATE_SUCCESS';
export const TEAMUPDATE_FAILURE = 'TEAMUPDATE_FAILURE';
export const TEAMDELETE_REQUEST = 'TEAMDELETE_REQUEST';
export const TEAMDELETE_SUCCESS = 'TEAMDELETE_SUCCESS';
export const TEAMDELETE_FAILURE = 'TEAMDELETE_FAILURE';
export const TEAMLIKE_REQUEST = 'TEAMLIKE_REQUEST';
export const TEAMLIKE_SUCCESS = 'TEAMLIKE_SUCCESS';
export const TEAMLIKE_FAILURE = 'TEAMLIKE_FAILURE';

export const PROSEARCH = 'PROSEARCH'
export const PROADD = 'PROADD';
export const PROUPDATE = 'PROUPDATE';
export const PRODELETE = 'PRODELETE';
export const PROLIKE = 'PROLIKE';

export const PROSEARCH_REQUEST = 'PROSEARCH_REQUEST';
export const PROSEARCH_SUCCESS = 'PROSEARCH_SUCCESS';
export const PROSEARCH_FAILURE = 'PROSEARCH_FAILURE';
export const PROADD_REQUEST = 'PROADD_REQUEST';
export const PROADD_SUCCESS = 'PROADD_SUCCESS';
export const PROADD_FAILURE = 'PROADD_FAILURE';
export const PROUPDATE_REQUEST = 'PROUPDATE_REQUEST';
export const PROUPDATE_SUCCESS = 'PROUPDATE_SUCCESS';
export const PROUPDATE_FAILURE = 'PROUPDATE_FAILURE';
export const PRODELETE_REQUEST = 'PRODELETE_REQUEST';
export const PRODELETE_SUCCESS = 'PRODELETE_SUCCESS';
export const PRODELETE_FAILURE = 'PRODELETE_FAILURE';
export const PROLIKE_REQUEST = 'PROLIKE_REQUEST';
export const PROLIKE_SUCCESS = 'PROLIKE_SUCCESS';
export const PROLIKE_FAILURE = 'PROLIKE_FAILURE';